version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet publish ./src/MentorBot.Api/MentorBot.Api.csproj -c Release
  - cmd: dotnet publish ./src/MentorBot.WebLearningCenter/MentorBot.WebLearningCenter.csproj -c Release
after_build:
  # For once the build has completed
artifacts:
 - path: '\src\MentorBot.Api\bin\Release\netcoreapp2.0\publish'
   name: MentorBotApi
   type: WebDeployPackage
 - path: '\src\MentorBot.WebLearningCenter\bin\Release\netcoreapp2.0\publish'
   name: MentorBotWebLearningCenter
   type: WebDeployPackage
clone_depth: 1
test_script
  # run the unit tests (requires changing into the test directory)
  - cmd: dotnet test ./tests/MentorBot.Tests/MentorBot.Tests.csproj
on_finish :
  # any cleanup in here
deploy: off
